-- tabela de dimensão de vendedor
CREATE TABLE IF NOT EXISTS DIM_VENDEDOR (
    sk_vendedor SERIAL PRIMARY KEY,
    nome_vendedor TEXT NOT NULL UNIQUE, 
    data_inclusao TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
COMMENT ON TABLE DIM_VENDEDOR IS 'Dimensão de Vendedores.';